# Profile information
name: Blog
title: Blog - Rachel Flynn
description: > # this means to ignore newlines until "baseurl:"
  Rachel Flynn's Blog. The Not So Secret Life of Rachel Flynn.
permalink: ':title/'
# baseurl: "/fresh" # the subpath of your site, e.g. /blog
homepage: https://flynnrachel.com
url: "flynnrachel.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: rachel.flynn.1212
instagram: rachelflynnnn
linkedin: rachelflynn27

# Contact form
email: mail@flynnrachel.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]